apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: c3JlZTEyMw==
  database-url: aG9zdD0zNC44My4xNzcuNDcgcG9ydD01NDMyIHVzZXI9cG9zdGdyZXMgcGFzc3dvcmQ9c3JlZTEyMyBkYm5hbWU9ZmluYW5jZV90cmFja2VyIHNzbG1vZGU9ZGlzYWJsZQ==
  test-database-url: aG9zdD0zNC44My4xNzcuNDcgcG9ydD01NDMyIHVzZXI9cG9zdGdyZXMgcGFzc3dvcmQ9c3JlZTEyMyBkYm5hbWU9ZmluYW5jZV90cmFja2VyX3Rlc3Qgc3NsbW9kZT1kaXNhYmxl
---
apiVersion: v1
kind: Secret
metadata:
  name: google-credentials
type: Opaque
data:
  client-id: MTAyNTgzMjEyNjg3NC05dDgzZmxqYzRrbW43ZW52ZzNmYml1OWV2dWZ2OXBsbC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQ==
  client-secret: R09DU1BYLUFPUXdhbmMxNjE2Z2h2Y2ZxUkRILWdwNFdGaDY=
---  
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  secret-key: YUFrWXJaOWdkT3U3ZjdEVk1KODhQWW5jeDRTMWlwR1UzWFFZT1ZIOU5ITT0=
  api-key: M2I0ZTRidmdub3I3OW90dmxrbDhvbzVibW8xNG9vYjhram4xYXU2bHV2Z2dmNHYzajcxZWk=